Add send message SC example
massalabs/massa-sc-examples pull request #13
Opened 2022-03-28 08:07 UTC by Eitu33

2022-03-28 08:10 UTC, Eitu33 commented
yarn.lock changes are there because the format has changed with the latest versions, thought I'd push it but maybe we want to keep the previous version?

2022-03-28 09:46 UTC, qdrn requested changes
You can also remove `.wat` and `.wasm.map` files as they are of no use.

2022-03-28 09:46 UTC, qdrn commented on package.json
> +    "massa-sc-std": "https://github.com/massalabs/massa-sc-std#5c90b49",
I don't think you want to use a specific branch. Let's just wait for the `massa-sc-std` branch with the `send_message` to be merged.

2022-03-31 13:37 UTC, Eitu33 commented
@qdrn should we merge this as it is or wait for https://github.com/massalabs/massa-sc-std/pull/11 to be completed in order to use the new version tag?

2022-04-04 15:08 UTC, gregLibert commented
@Eitu33 you should remove (add to gitignore + delete) wasm files also.

2022-04-15 07:11 UTC, Eitu33 commented
> @Eitu33 you should remove (add to gitignore + delete) wasm files also.

I don't agree, if someone wants a ready to go example SC wasm to test out something they have that possibility without needing to compile anything (which has a few prerequisites).

2022-04-15 07:45 UTC, yvan-sraka commented
We can put `.WASM` files, and other binaries artifacts under Git LFS management, if we want to track them here :)

2022-04-19 14:20 UTC, qdrn approved these changes

2022-04-19 14:20 UTC, merged