change provider logic
massalabs/massa-sc-examples pull request #149
Opened 2023-07-19 13:23 UTC by lilyanB

accept providers:

![image](https://github.com/massalabs/massa-sc-examples/assets/91454320/4814b246-3998-49ab-abd5-e5a2ee7e21ec)

2023-07-20 08:02 UTC, gregLibert requested changes

2023-07-20 08:02 UTC, gregLibert commented on sum/front/src/hooks/useMassaStation.ts
As providers name are fetch asyncrhonously and that the detection can take some time, do you think that we should add a loading message ?
I didn't tested it if we plan to let massa-web3 wait for 0,5s to 1 s to fetch the data (to be confirmer by @Elli610 ) in that case, I think we should also add that.

2023-07-20 12:41 UTC, lilyanB commented on sum/front/src/hooks/useMassaStation.ts
> +                console.log("providerslist", providerslist.length);
Oh! Sorry, I forgot to push the last version
done

2023-07-20 12:41 UTC, lilyanB commented on sum/front/src/hooks/useMassaStation.ts
> +                    console.log("ici");
Oh! Sorry, I forgot to push the last version
done

2023-07-20 12:43 UTC, lilyanB commented on sum/front/src/components/body.tsx
> +        const account = accountOption?.find(
done

2023-07-20 12:44 UTC, lilyanB commented on sum/front/src/components/body.tsx
> +        const provider = option?.find(
okai, I understand. Thanks
done

2023-07-20 12:44 UTC, lilyanB commented on sum/front/src/components/body.tsx
> +    const handleSelectChangeAccount = (
done

2023-07-20 12:45 UTC, lilyanB commented on sum/front/src/components/body.tsx
> +    const handleSelectChangeProvider = (
done

2023-07-20 12:47 UTC, lilyanB commented on sum/front/src/components/body.tsx
> +    const [accountOption, setAccountOption] = useState<IAccount[]>();
done

2023-07-20 12:49 UTC, lilyanB commented on sum/front/src/components/body.tsx
> +    const [option, setOption] = useState<IProvider[] | null>(null);
done

2023-07-20 13:07 UTC, lilyanB commented on sum/front/src/hooks/useMassaStation.ts
We talked about it. Currently, the Wallet-provider search for 10sec(We have chosen this option, but it can be modified.) and returns an empty list if nothing has been found.
During this time, I display this paragraph displayed:
```ts
                        <p className="bodyInformationRed">
                            loading provider and wallet
                        </p>
```

![image](https://github.com/massalabs/massa-sc-examples/assets/91454320/320210ec-42d9-4b80-9406-c0c436436d7b)


And I display this error message:
![image](https://github.com/massalabs/massa-sc-examples/assets/91454320/a5638743-c4dc-4b2b-816b-506689c916fa)

2023-07-20 14:35 UTC, lilyanB commented
I didn't change the sum contract. The deployment error display: "Error: Invalid params".  I created an Issue

2023-07-20 16:13 UTC, gregLibert commented
Still not working:
![image](https://github.com/massalabs/massa-sc-examples/assets/16623956/6dcae3ee-0a62-456d-8c08-c0676daf114f)
The front is saying that there is no provider, but massa station is return an http 200 (ok)

2023-07-24 07:42 UTC, lilyanB commented
> Still not working: ![image](https://user-images.githubusercontent.com/16623956/254943825-6dcae3ee-0a62-456d-8c08-c0676daf114f.png) The front is saying that there is no provider, but massa station is return an http 200 (ok)

@gregLibert 
It's working for me with the new version of the provider and some argument

2023-07-24 07:58 UTC, gregLibert commented
On failure, the div containing `loading provider and wallet` should be updated to something like `no provider detected`.

![image](https://github.com/massalabs/massa-sc-examples/assets/16623956/1c519251-121a-41b4-afd8-67126234e368)

2023-07-24 08:00 UTC, gregLibert commented
I also have an uncatch error when massa station is installed, but not massa wallet:
![image](https://github.com/massalabs/massa-sc-examples/assets/16623956/608e91eb-af62-47ea-8d20-1386806c7193)

2023-07-24 08:02 UTC, gregLibert commented
Can you add a  meaninful animation around `loading provider and wallet` to show that something is ongoing ?

2023-07-24 08:02 UTC, gregLibert commented
i fyou also can remove the red everywhere and keep it only for error. This will improve readibility

2023-07-24 08:03 UTC, gregLibert requested changes
See comments

2023-07-24 10:01 UTC, lilyanB commented
> i fyou also can remove the red everywhere and keep it only for error. This will improve readability

I remove the red and put another color? or no color?

2023-07-25 10:12 UTC, gregLibert requested changes
Nothing happens when I click on the sum button. Aren't we supposed to call the smart contract ?

Furthermore, there si code smell and Ci is broken

2023-07-25 14:44 UTC, Ben-Rey commented
Ci fixed !

2023-07-25 14:44 UTC, Elli610 commented
> Nothing happens when I click on the sum button. Aren't we supposed to call the smart contract ?


The functionality for the caller has not been implemented yet. However, once the massa-proto-cli is ready, I'll make sure to update it accordingly.

2023-07-25 17:25 UTC, gregLibert requested changes
Two small changes: we need massa for it to work.
This should be also added in the READme i guess.

furthermore, eadibility should be imporve (but this is to be done in another PR)
After that, @Ben-Rey you can safely merge!

2023-07-25 17:25 UTC, gregLibert commented on sum/front/src/components/contractInteraction.tsx
> +                BigInt(0)
```suggestion
                BigInt(1)
```

2023-07-25 17:25 UTC, gregLibert commented on sum/front/src/components/contractInteraction.tsx
> +            BigInt(0),
maybe:
```suggestion
            BigInt(0),
```

2023-07-25 17:40 UTC, Ben-Rey approved these changes

2023-07-26 08:43 UTC, gregLibert approved these changes

2023-07-26 09:20 UTC, merged