update sum for testnet17
massalabs/massa-sc-examples pull request #41
Opened 2022-12-05 16:22 UTC by Thykof

2022-12-05 17:47 UTC, gregLibert requested changes
:no_good: as-tester is leaving. We should replace it by as-pect as soon as possible.
:camping: some typos

2022-12-05 17:47 UTC, gregLibert commented on sum/contracts/README.md
> +To use librairies as massa-as-sdk and @massalabs/as you need to import the required function, for instance :
```suggestion
To use libraries like @massalabs/massa-as-sdk and @massalabs/as, you need to import the required function, for instance:
```

2022-12-05 17:47 UTC, gregLibert commented on sum/contracts/asconfig.json
> +        "transform": ["@massalabs/as-transformer/file2ByteArray.js", "@massalabs/as-tester/check_replacer.js"]
```suggestion
        "transform": ["@massalabs/as-transformer/file2ByteArray.js"]
```

2022-12-05 17:47 UTC, gregLibert commented on sum/contracts/assembly/__test__/main.ts
>  import { Args } from "@massalabs/massa-as-sdk";
You should use aspect.

2022-12-05 17:47 UTC, gregLibert commented on sum/contracts/deployer/deployer.ts
> +            throw new Error("WALLET_PRIVATE_KEY is not set. Did you create environment file \".env\" ?");
```suggestion
            throw new Error("WALLET_PRIVATE_KEY is not set. Did you create an environment file `.env`?");
```

2022-12-05 17:47 UTC, gregLibert commented on sum/contracts/package.json
> +        "@massalabs/as-tester": "^0.0.3-dev",
bye bye!

2022-12-06 10:37 UTC, Thykof commented on sum/contracts/README.md
> +Call it:
I mean run the deployed smart contract

2022-12-06 10:39 UTC, Thykof commented
To migrate to as-pect, we need first to update our toolkit with as-pect. So I suggest to merge this PR so that to documentation and example are working asap, then I will work on the toolkit and then on make as-pect for this example

2022-12-06 17:33 UTC, gregLibert approved these changes
:man_shrugging: LGTM

2022-12-06 17:33 UTC, gregLibert commented on sum/contracts/asconfig.json
> +        "transform": ["@massalabs/as-transformer/file2ByteArray.js", "@massalabs/as-tester/check_replacer.js"]
@Thykof do you really want to keep the check_replacer ?

2022-12-06 17:33 UTC, gregLibert commented on sum/contracts/deployer/deployer.ts
> +        const base64: string = Buffer.from(binaryFileContents).toString("base64");
I think because we need to. Right now it's the only way to deploy a SC using the massa-web3 library. But maybe it was updated...

2022-12-07 09:02 UTC, Thykof commented
I have removed the check replacer transformer in commit [68043ab](https://github.com/massalabs/massa-sc-examples/pull/41/commits/68043aba9146c73b5ec144e1d20beb7fc8023024) and the last commit is only about formatting.

2022-12-07 09:14 UTC, peterjah commented on sum/contracts/deployer/deployer.ts
> +        const base64: string = Buffer.from(binaryFileContents).toString("base64");
we need to what ?
i just mean that the code present before was totally equivalent:
why replace:
`
const contractDataBase64 = fs.readFileSync(contractWasm, "base64");
`
by this
`
    const binaryArrayBuffer: Buffer = fs.readFileSync(contractWasm, {});
    const binaryFileContents = new Uint8Array(binaryArrayBuffer);
    const base64: string = Buffer.from(binaryFileContents).toString("base64");
    `
 the result is the same :/

2022-12-07 09:16 UTC, peterjah commented on sum/contracts/deployer/deployer.ts
> +        const base64: string = Buffer.from(binaryFileContents).toString("base64");
at least i think so ^^

2022-12-07 09:36 UTC, Thykof commented on sum/contracts/simulator/simulate.js
>  const TESTER_RELEASE_URL =
good catch it is now removed

2022-12-07 09:37 UTC, SebastienValla approved these changes

2022-12-07 10:02 UTC, merged

2022-12-07 10:03 UTC, Thykof commented on sum/contracts/deployer/deployer.ts
> +        const base64: string = Buffer.from(binaryFileContents).toString("base64");
you are right

2022-12-19 16:55 UTC, Thykof commented
Follow up task https://github.com/massalabs/massa-sc-examples/issues/42